Add RGB, ARGB and RGBA methods for the category of UIColor.
yahoo/AppDevKit pull request #65
Opened 2017-10-23 07:26 UTC by joehsieh

2017-10-23 07:26 UTC, yahoocla commented
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

2017-10-24 08:30 UTC, qcl requested changes
I'd done my review. And I hope you can also complete the test for those new methods.

2017-10-24 08:30 UTC, qcl commented on AppDevPods/AppDevCommonKit/UIColor+ADKHexPresentation.h
> + *        The behaviour is the same as ADKColorWithRGBHexString:, but ADKColorWithRGBHexString is preferred.
Second `ADKColorWithRGBHexString` missed its `:`.

2017-10-25 06:31 UTC, joehsieh commented
I've fixed the typo and applied related tests.

2017-10-25 06:33 UTC, joehsieh commented
BTW, I also upgrade IPHONEOS_DEPLOYMENT_TARGET of test target from 7.0 to 8.0 to build the tests successfully.

2017-10-25 06:54 UTC, qcl requested changes
I'd done my review.

2017-10-25 06:54 UTC, qcl commented on AppDevKitTests/AppDevCommonKit/UIColor+ADKHexPresentationSpec.m
> +    it(@"given color with 7b0099, should get string 7B0099", ^{
It should be `given string 7B0099, should get color with 7b0099`.

2017-10-25 06:54 UTC, qcl commented on AppDevKitTests/AppDevCommonKit/UIColor+ADKHexPresentationSpec.m
> +    it(@"given color with EE7b0099, should get string EE7B0099", ^{
Ditto.

2017-10-25 06:54 UTC, qcl commented on AppDevKitTests/AppDevCommonKit/UIColor+ADKHexPresentationSpec.m
> +    it(@"given color with 7b0099EE, should get string 7B0099EE", ^{
Ditto.

2017-10-25 06:57 UTC, joehsieh commented
I've updated the test description. Thanks.

2017-10-25 07:19 UTC, qcl approved these changes
👍

2017-10-25 07:19 UTC, merged